:-include('com/prolog/sokoban/sokobanLarg.pl').
liaison(bb,cb).
liaison(bb,bc).
liaison(bc,cc).
liaison(cb,db).
liaison(cb,cc).
liaison(cc,dc).
liaison(cc,cd).
liaison(cd,dd).
liaison(cd,ce).
liaison(ce,de).
liaison(db,dc).
liaison(dc,dd).
liaison(dd,ed).
liaison(dd,de).
liaison(ed,fd).
liaison(fb,gb).
liaison(fb,fc).
liaison(fc,gc).
liaison(fc,fd).
liaison(fd,gd).
liaison(fd,fe).
liaison(fe,ge).
liaison(fe,ff).
liaison(ff,gf).
liaison(gb,hb).
liaison(gb,gc).
liaison(gc,hc).
liaison(gc,gd).
liaison(gd,hd).
liaison(gd,ge).
liaison(ge,he).
liaison(ge,gf).
liaison(gf,hf).
liaison(hb,hc).
liaison(hc,hd).
liaison(hd,id).
liaison(hd,he).
liaison(he,ie).
liaison(he,hf).
liaison(id,ie).

sokoban(ChSol):-sokoban(ie,[dc,gd],[gb,gc],[],10,ChSol).
:- open('solution',write,OS), sokoban(ChSol), write(OS,ChSol), halt.
